"""Conservative local relation arbiter for 6.0.0-test5.

Stages:
  1. Hard constraints (already computed by ThreadEvidence)
  2. Evidence fusion (from EvidenceResult.fused)
  3. Candidate interval: accepted / provisional / rejected / unrelated_similar
  4. Relation type inference and edge write

test1 relations that can be auto-accepted:
  retells, parallel, unrelated_similar, continues (with source evidence)
Other relations (causes, supersedes, resolves, breaks) stay provisional.
"""
from __future__ import annotations

import json
import logging
import time
import uuid
from typing import Any

from .thread_evidence import ThreadEvidence, EvidenceResult

logger = logging.getLogger(__name__)

# Thresholds (conservative, no LLM in test1)
ACCEPT_THRESHOLD = 0.82
ACCEPT_GAP = 0.15           # must lead runner-up by this margin
# Real-data calibration: scores below 0.42 were overwhelmingly generated by
# ubiquitous protagonist entities and date proximity alone. Sending those to
# the LLM creates quadratic queue growth without useful thread evidence.
REJECT_THRESHOLD = 0.42
ARBITER_VERSION = "test5-local-v2"

_CAUSAL_RELATIONS = {"causes", "supersedes", "resolves", "breaks"}
_AUTO_ALLOWED = {"retells", "parallel", "unrelated_similar", "continues"}


class ThreadArbiter:
    """Local four-stage arbiter. Returns edge dict or None."""

    def __init__(self):
        self._evidence = ThreadEvidence()

    # ----------------------------------------------------------------------- #
    #  public                                                                   #
    # ----------------------------------------------------------------------- #

    def decide(self, ep_a: dict, ep_b: dict, *, candidate_gap: float | None = None,
               scope_id: str = "") -> dict[str, Any] | None:
        """Return an edge dict ready for ThreadStore.insert_edge(), or None."""
        res = self._evidence.compute(ep_a, ep_b)
        if res.hard_reject:
            return self._edge(ep_a, ep_b, "rejected", 0.0, res,
                              note=res.reject_reason, scope_id=scope_id)

        score = res.fused
        relation, direction = self._infer_relation(ep_a, ep_b, res)

        if score < REJECT_THRESHOLD:
            return self._edge(ep_a, ep_b, "rejected", score, res,
                              relation=relation, note="score_below_threshold", scope_id=scope_id)

        # Exact source-turn overlap plus semantic agreement can prove a retell.
        # Merely sharing a compression batch cannot.
        if (res.e >= 0.95 and res.b >= 0.65
                and not bool(res.details.get("date_conflict"))):
            return self._edge(ep_a, ep_b, "accepted", max(score, 0.92), res,
                              relation="retells", direction="none", scope_id=scope_id)
        if relation in _CAUSAL_RELATIONS:
            return self._edge(ep_a, ep_b, "provisional", score, res,
                              relation=relation, note="causal_requires_llm", scope_id=scope_id)

        # A non-source auto decision must both clear the threshold and lead the
        # next candidate. Without a computed gap it remains provisional.
        if score >= ACCEPT_THRESHOLD and candidate_gap is not None and candidate_gap >= ACCEPT_GAP:
            return self._edge(ep_a, ep_b, "accepted", score, res,
                              relation=relation, direction=direction, scope_id=scope_id)

        # Middle ground → provisional
        return self._edge(ep_a, ep_b, "provisional", score, res,
                          relation=relation, direction=direction, scope_id=scope_id)

    # ----------------------------------------------------------------------- #
    #  relation inference                                                       #
    # ----------------------------------------------------------------------- #

    def _infer_relation(self, ep_a: dict, ep_b: dict,
                         res: EvidenceResult) -> tuple[str, str]:
        score = res.fused
        ts_a = float(ep_a.get("event_ts") or 0)
        ts_b = float(ep_b.get("event_ts") or 0)

        # Exact source overlap is the only source-only retell route.
        if res.e >= 0.95 and not bool(res.details.get("date_conflict")):
            return "retells", "none"

        same_batch = bool(ep_a.get("source_batch_id")) and (
            str(ep_a.get("source_batch_id")) == str(ep_b.get("source_batch_id"))
        )
        if same_batch:
            return "parallel", "none"

        # Very high entity + semantic with same-day temporal → retells
        if res.a >= 0.60 and res.b >= 0.70 and res.c >= 0.80:
            return "retells", "none"

        # High entity but low temporal (different dates) → parallel or distinct
        if res.a >= 0.40 and res.c <= 0.20 and res.d < 0.25 and res.b < 0.60:
            return "unrelated_similar", "none"

        # Decent overall, sequential time → continues
        if score >= 0.40 and ts_a > 0 and ts_b > 0 and abs(ts_a - ts_b) < 90 * 86400:
            if ts_a < ts_b:
                return "continues", "a_to_b"
            elif ts_b < ts_a:
                return "continues", "b_to_a"

        if score >= 0.40:
            return "parallel", "none"

        return "unrelated_similar", "none"

    # ----------------------------------------------------------------------- #
    #  edge dict builder                                                        #
    # ----------------------------------------------------------------------- #

    @staticmethod
    def _edge(ep_a: dict, ep_b: dict, status: str, score: float,
              res: EvidenceResult, *, relation: str = "parallel",
              direction: str = "none", note: str = "", scope_id: str = "") -> dict[str, Any]:
        a_id = str(ep_a.get("episode_id") or "")
        b_id = str(ep_b.get("episode_id") or "")
        if direction == "b_to_a":
            a_id, b_id = b_id, a_id
            direction = "directed"
        elif direction == "a_to_b":
            direction = "directed"
        elif a_id > b_id:
            a_id, b_id = b_id, a_id
        return {
            "source_episode_id": a_id,
            "target_episode_id": b_id,
            "scope_id": str(scope_id or ep_a.get("scope_id") or ep_b.get("scope_id") or "default"),
            "edge_type": relation,
            "direction": direction,
            "confidence": round(score, 4),
            "status": status,
            "evidence_json": json.dumps(res.to_dict(), ensure_ascii=False, default=str),
            "counter_evidence_json": "[]",
            "route_sources_json": json.dumps(
                ["A", "B", "C", "D", "E"], ensure_ascii=False),
            "arbiter_version": ARBITER_VERSION,
            "decision_source": "rule",
            "manual_lock": 0,
            "created_ts": time.time(),
            "updated_ts": time.time(),
            "_note": note,
        }
